host = "localhost"
host = ${?HOST}

port = 3000
port = ${?PORT}

weather {
  feels-like-hot-threshold-f = 75.0
  feels-like-hot-threshold-f = ${?WEATHER_FEELS_LIKE_HOT_THRESHOLD_F}

  feels-like-cold-threshold-f = 60.0
  feels-like-cold-threshold-f = ${?WEATHER_FEELS_LIKE_COLD}
}
